import os
import sys
os.system("apt install figlet")
os.system("clear")
os.system("figlet Bruteforce")
print ("")
print ("      +---------------------")
print ("      !Made by:Min May lol!")
print ("      +--------------------+")
print ("")
a = input("id/email>>")
b = input("pasword>>")
print("")
print ("hacking starting...10 ")
os.system("sleep 3")
print ("hacking starting...20 ")
os.system("sleep 3")
print ("hacking starting...30 ")
os.system("sleep 3")
print ("hacking starting...40 ")
os.system("sleep 3")
print ("hacking starting...50 ")
os.system("sleep 3")
print ("hacking starting...80 ")
print ("hacking starting...90 ")
print ("Hack Done... ")
os.system("sleep 3")
os.system("clear")
os.system("figlet Min May Hack")
print ("")
print ("             min may sout phoat hack 20%")
os.system("sleep 3")
print ("             min may sout phoat hack 40%")
os.system("sleep 3")
print ("             min may sout phoat hack 60%")
os.system("sleep 3")
print ("             min may sout phoat hack 80%")
os.system("sleep 3")
print ("             min may sout phoat hack 100%")
os.system("sleep 7")
print ("             min may sout phoat hack Done....")
os.system("sleep 10")
print ("")
print ("              +-----------------------")
print ("              !passwod=minmaysoutphot!")
print ("              +----------------------+")
